### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by karan** [charlierguo/gmail#6]
What are the dependencies required for the package to work? Consider adding a requirements.txt file?

**Comment by charlierguo** [comment]
So currently there are no external dependencies, other than Python 2 (2.7 and above). What's the best way to specify the minimum Python version?

**Comment by joelgallant** [comment]
In your readme in [Installation](https://github.com/charlierguo/gmail#installation).

**Comment by karan** [comment]
Yes, in readme.

And after adding any external dependencies, use `pip freeze > requirements.txt` to create the said file.

**Comment by charlierguo** [comment]
Great, thanks!
